name       : poppler
version    : 0.55.0
release    : 10
source     :
    - https://poppler.freedesktop.org/poppler-0.55.0.tar.xz : 537f2bc60d796525705ad9ca8e46899dcc99c2e9480b80051808bae265cdc658
homepage   : http://poppler.freedesktop.org/
license    : GPL-2.0
component  : desktop.library
summary    : PDF Rendering Library
description: |
    PDF Rendering Library
builddeps  :
    - pkgconfig(fontconfig)
    - pkgconfig(freetype2)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(lcms2)
    - pkgconfig(libcurl)
    - pkgconfig(libopenjp2)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(nss)
    - pkgconfig(Qt5Core)
    - pkgconfig(QtCore)
    - libjpeg-turbo-devel
setup      : |
    %configure --disable-static \
        --enable-libcurl \
        --enable-libtiff \
        --enable-libopenjpeg=openjpeg2 \
        --enable-libpng \
        --enable-poppler-qt5 \
        --enable-poppler-qt4 \
        --enable-xpdf-headers \
        --enable-cmyk
patterns   :
    - qt5-devel :
        - /usr/include/poppler/qt5/
        - /usr/lib64/lib*qt5*.so
        - /usr/lib64/pkgconfig/*qt5*.pc
    - qt5 :
        - /usr/lib64/lib*qt5*.so.*
    - qt4-devel :
        - /usr/include/poppler/qt4/
        - /usr/lib64/lib*qt4*.so
        - /usr/lib64/pkgconfig/*qt4*.pc
    - qt4 :
        - /usr/lib64/lib*qt4*.so.*
    - utils :
        - /usr/bin
        - /usr/share/man
build      : |
    %make
install    : |
    %make_install
    rm $installdir/usr/bin/poppler-glib-demo
