name        : poppler
version     : 0.34.0
release     : 7
source      :
    - http://poppler.freedesktop.org/poppler-0.34.0.tar.xz : 1ba4ba9a2f9eb1e62ee6d736f4d82be4fc5f6dd177dc2b03febbe2ef2e515cb0
homepage    : http://poppler.freedesktop.org/
license     : GPL-2.0
summary     : PDF Rendering Library
description : |
    PDF Rendering Library
builddeps   :
    - pkgconfig(freetype2)
    - pkgconfig(fontconfig)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(lcms2)
    - pkgconfig(libcurl)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(Qt5Core)
    - libjpeg-turbo-devel
setup      : |
    %configure --disable-static \
        --enable-libcurl \
        --enable-libtiff \
        --enable-libjpeg \
        --enable-libpng \
        --enable-poppler-qt5 \
        --enable-xpdf-headers \
        --disable-libopenjpeg
build      : |
    %make
install    : |
    %make_install
