name       : poppler
version    : '0.60'
release    : 14
source     :
    - https://poppler.freedesktop.org/poppler-0.60.0.tar.xz : 1570774f44ba86c42ffacc5d9151a771e99584a55e6631bdf267123a2aed1c72
    - git|git://git.freedesktop.org/git/poppler/test : 0d2bfd4af4c76a3bac27ccaff793d9129df7b57a
homepage   : http://poppler.freedesktop.org/
license    : GPL-2.0
component  : desktop.library
summary    : PDF Rendering Library
description: |
    PDF Rendering Library
builddeps  :
    - pkgconfig(fontconfig)
    - pkgconfig(freetype2)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(lcms2)
    - pkgconfig(libcurl)
    - pkgconfig(libopenjp2)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(nss)
    - pkgconfig(Qt5Core)
    - libjpeg-turbo-devel
patterns   :
    - qt5-devel :
        - /usr/include/poppler/qt5/
        - /usr/lib64/lib*qt5*.so
        - /usr/lib64/pkgconfig/*qt5*.pc
    - qt5 :
        - /usr/lib64/lib*qt5*.so.*
    - utils :
        - /usr/bin
        - /usr/share/man
setup      : |
    # Test may need access to X
    sed -i '/check_qt5_password/d' qt5/tests/CMakeLists.txt
    %cmake -DTESTDATADIR=$sources/test.git \
           -DLIB_SUFFIX=%LIBSUFFIX% \
           -DENABLE_XPDF_HEADERS=ON
build      : |
    %make
install    : |
    %make_install
check      : |
    %make test
