name       : poppler
version    : 0.49.0
release    : 12
source     :
    - https://poppler.freedesktop.org/poppler-0.49.0.tar.xz : 14485f0e1e43dcddf49cfc02c2ccb92910ba3e0e91e06f4bd2642ec00cb3a79f
homepage   : http://poppler.freedesktop.org/
license    : GPL-2.0
component  : desktop.library
summary    : PDF Rendering Library
description: |
    PDF Rendering Library
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(fontconfig)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(lcms2)
    - pkgconfig(libcurl)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(Qt5Core)
    - pkgconfig(QtCore)
    - libjpeg-turbo-devel
setup      : |
    %patch -p1 < $pkgfiles/security/cve-2017-7511.patch
    %configure --disable-static \
        --enable-libcurl \
        --enable-libtiff \
        --enable-libjpeg \
        --enable-libpng \
        --enable-poppler-qt5 \
        --enable-poppler-qt4 \
        --enable-xpdf-headers \
        --disable-libopenjpeg
patterns   :
    - qt5-devel :
        - /usr/include/poppler/qt5/
        - /usr/lib64/lib*qt5*.so
        - /usr/lib64/pkgconfig/*qt5*.pc
    - qt5 :
        - /usr/lib64/lib*qt5*.so.*
    - qt4-devel :
        - /usr/include/poppler/qt4/
        - /usr/lib64/lib*qt4*.so
        - /usr/lib64/pkgconfig/*qt4*.pc
    - qt4 :
        - /usr/lib64/lib*qt4*.so.*
    - utils :
        - /usr/bin
        - /usr/share/man
build      : |
    %make
install    : |
    %make_install
    rm $installdir/usr/bin/poppler-glib-demo
