name       : poppler
version    : 22.06.0
release    : 42
source     :
    - https://poppler.freedesktop.org/poppler-22.06.0.tar.xz : a0f9aaa3918bad781039fc307a635652a14d1b391cd559b66edec4bedba3c5d7
    - git|https://gitlab.freedesktop.org/poppler/test.git : 920c89f8f43bdfe8966c8e397e7f67f5302e9435
license    : GPL-2.0-or-later
component  :
    - desktop.library
    - qt5 : desktop.library
    - utils : office
homepage   : http://poppler.freedesktop.org/
summary    : PDF Rendering Library
description: |
    PDF Rendering Library
patterns   :
    - qt5-devel :
        - /usr/include/poppler/qt5/
        - /usr/lib64/lib*qt5*.so
        - /usr/lib64/pkgconfig/*qt5*.pc
    - qt5 :
        - /usr/lib64/lib*qt5*.so.*
    - utils :
        - /usr/bin
        - /usr/share/man
builddeps  :
    - pkgconfig(fontconfig)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(poppler-data)
    - pkgconfig(lcms2)
    - pkgconfig(libcurl)
    - pkgconfig(libopenjp2)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(nss)
    - pkgconfig(Qt5Core)
    - libboost-devel
rundeps    :
    - poppler-data
    - devel :
        - poppler-utils
    - qt5-devel :
        - poppler-qt5
setup      : |
    %cmake -DTESTDATADIR=$sources/test.git \
           -DLIB_SUFFIX=%LIBSUFFIX% \
           -DENABLE_UNSTABLE_API_ABI_HEADERS=ON
build      : |
    %make
install    : |
    %make_install
check      : |
    %make test
