name       : poppler
version    : 21.03.0
release    : 31
source     :
    - https://gitlab.freedesktop.org/poppler/poppler/-/archive/poppler-21.03.0/poppler-poppler-21.03.0.tar.gz : a6a17b92406448ab869191b46e04fcb1d79f479df3beb9d807c81a0de070eb25
    - git|git://git.freedesktop.org/git/poppler/test : 03a4b9eb854a06a83c465e82de601796c458bbe9
homepage   : http://poppler.freedesktop.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : PDF Rendering Library
description: |
    PDF Rendering Library
builddeps  :
    - pkgconfig(fontconfig)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(poppler-data)
    - pkgconfig(lcms2)
    - pkgconfig(libcurl)
    - pkgconfig(libopenjp2)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(nss)
    - pkgconfig(Qt5Core)
    - libboost-devel
rundeps    :
    - poppler-data
    - devel :
        - poppler-utils
    - qt5-devel :
        - poppler-qt5
patterns   :
    - qt5-devel :
        - /usr/include/poppler/qt5/
        - /usr/lib64/lib*qt5*.so
        - /usr/lib64/pkgconfig/*qt5*.pc
    - qt5 :
        - /usr/lib64/lib*qt5*.so.*
    - utils :
        - /usr/bin
        - /usr/share/man
setup      : |
    %cmake -DTESTDATADIR=$sources/test.git \
           -DLIB_SUFFIX=%LIBSUFFIX% \
           -DENABLE_UNSTABLE_API_ABI_HEADERS=ON
build      : |
    %make
install    : |
    %make_install
check      : |
    %make test
