name       : poppler
version    : 0.60.1
release    : 25
source     :
    - https://gitlab.freedesktop.org/poppler/poppler/-/archive/poppler-0.60.1/poppler-poppler-0.60.1.tar.bz2 : 6490d4a401636f3a9c5bbdb397b3776b0638a208cd21fc0d829d5a92bc4739e8
    - git|git://git.freedesktop.org/git/poppler/test : 0d2bfd4af4c76a3bac27ccaff793d9129df7b57a
homepage   : http://poppler.freedesktop.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : PDF Rendering Library
description: |
    PDF Rendering Library
builddeps  :
    - pkgconfig(fontconfig)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(lcms2)
    - pkgconfig(libcurl)
    - pkgconfig(libopenjp2)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(nss)
    - pkgconfig(Qt5Core)
rundeps    :
    - poppler-data
    - devel :
        - poppler-utils
    - qt5-devel :
        - poppler-qt5
patterns   :
    - qt5-devel :
        - /usr/include/poppler/qt5/
        - /usr/lib64/lib*qt5*.so
        - /usr/lib64/pkgconfig/*qt5*.pc
    - qt5 :
        - /usr/lib64/lib*qt5*.so.*
    - utils :
        - /usr/bin
        - /usr/share/man
setup      : |
    %apply_patches
    # Test may need access to X
    sed -i '/check_qt5_password/d' qt5/tests/CMakeLists.txt
    %cmake -DTESTDATADIR=$sources/test.git \
           -DLIB_SUFFIX=%LIBSUFFIX% \
           -DENABLE_XPDF_HEADERS=ON
build      : |
    %make
install    : |
    %make_install
check      : |
    %make test
