name       : poppler
version    : 22.01.0
release    : 37
source     :
    - https://poppler.freedesktop.org/poppler-22.01.0.tar.xz : 7d3493056b5b86413e5c693c2cae02c5c06cd8e618d14c2c31e2c84b67b2313e
    - git|https://gitlab.freedesktop.org/poppler/test.git : 0762e0144143e680e24ec8d4c34c46c3716b8713
license    : GPL-2.0-or-later
component  : desktop.library
homepage   : http://poppler.freedesktop.org/
summary    : PDF Rendering Library
description: |
    PDF Rendering Library
patterns   :
    - qt5-devel :
        - /usr/include/poppler/qt5/
        - /usr/lib64/lib*qt5*.so
        - /usr/lib64/pkgconfig/*qt5*.pc
    - qt5 :
        - /usr/lib64/lib*qt5*.so.*
    - utils :
        - /usr/bin
        - /usr/share/man
builddeps  :
    - pkgconfig(fontconfig)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(poppler-data)
    - pkgconfig(lcms2)
    - pkgconfig(libcurl)
    - pkgconfig(libopenjp2)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(nss)
    - pkgconfig(Qt5Core)
    - libboost-devel
rundeps    :
    - poppler-data
    - devel :
        - poppler-utils
    - qt5-devel :
        - poppler-qt5
setup      : |
    %cmake -DTESTDATADIR=$sources/test.git \
           -DLIB_SUFFIX=%LIBSUFFIX% \
           -DENABLE_UNSTABLE_API_ABI_HEADERS=ON
build      : |
    %make
install    : |
    %make_install
check      : |
    %make test
