name       : poppler
version    : 0.75.0
release    : 27
source     :
    - https://gitlab.freedesktop.org/poppler/poppler/-/archive/poppler-0.75.0/poppler-poppler-0.75.0.tar.bz2 : 16c794af3e1299bb31dedb7b501196a85cad5a469631a20d537ee21dbb51718d
    - git|git://git.freedesktop.org/git/poppler/test : 45f55f1e03b9bf3fbd334c31776b6f5e472889ec
homepage   : http://poppler.freedesktop.org/
license    : GPL-2.0-or-later
component  : desktop.library
summary    : PDF Rendering Library
description: |
    PDF Rendering Library
builddeps  :
    - pkgconfig(fontconfig)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(lcms2)
    - pkgconfig(libcurl)
    - pkgconfig(libopenjp2)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(nss)
    - pkgconfig(Qt5Core)
rundeps    :
    - poppler-data
    - devel :
        - poppler-utils
    - qt5-devel :
        - poppler-qt5
patterns   :
    - qt5-devel :
        - /usr/include/poppler/qt5/
        - /usr/lib64/lib*qt5*.so
        - /usr/lib64/pkgconfig/*qt5*.pc
    - qt5 :
        - /usr/lib64/lib*qt5*.so.*
    - utils :
        - /usr/bin
        - /usr/share/man
setup      : |
    %patch -p1 < $pkgfiles/fix-segfault-with-digitally-signed-pdfs.patch
    %cmake -DTESTDATADIR=$sources/test.git \
           -DLIB_SUFFIX=%LIBSUFFIX% \
           -DENABLE_UNSTABLE_API_ABI_HEADERS=ON
build      : |
    %make
install    : |
    %make_install
check      : |
    %make test
